require "rake"
$LOAD_PATH <<   File.join(File.dirname(__FILE__), "lib")


#This task is used for generating the pdf file of one html page
#It's using the wkpdf gem that works on ruby 1.8 with the cocoa integration
#We must run it using the system ruby with rvm
#It's also using the too pdftk for merging the pdf files into one
#Remember to run "rvm use system" before executing
desc "Generate PDF of one slide file"
task :toPDF, [:slide] do |t, args|
  puts "First name is #{args.slide}"
  filename = "#{Dir.pwd}/#{args.slide}"
  system 'mkdir tmp_pdf'
  sections = File.readlines(filename).grep(/div.+class.+step/)
  ids = Array.new(sections.length) {|i| (i+1).to_s }
  sections.each_with_index {|l,i| l.match(/id='(\w+)'/){|m| ids[i] = m[1]} }
  
  ids.each do |i|
    puts "'file://localhost#{filename}##{i}'"
    #system "rvm system exec wkpdf --source 'file://localhost#{filename}##{i}' --orientation landscape --paper b4 --margins 0 --output tmp_pdf/#{args.slide}-#{i}.pdf" 
  end
  #system "pdftk tmp_pdf/*.pdf cat output ../public/docs/#{args.slide}.pdf"
  #system 'rm -rf tmp_pdf'
end
  
